name: Deploy to Surge

on:
  push:
    branches: [ "main" ]   
  workflow_dispatch:       

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Surge CLI
        run: npm i -g surge

    

      - name: Deploy to surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}   
          SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }} 
        run: surge --project . --domain "$SURGE_DOMAIN" --token "$SURGE_TOKEN"
